name: contactus
description: contactus is the package which helps the developers to add their
  contact information with ease.Developers can add many important details such
  as website, email, phone number, etc.
version: 1.2.1
repository: https://github.com/AbhishekDoshi26/contactus
homepage: https://abhishekdoshi.netlify.app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  typicons_flutter: ^0.5.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
